/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_draculaw_yeplayer_YePlayerHelper */

#ifndef _Included_com_draculaw_yeplayer_YePlayerHelper
#define _Included_com_draculaw_yeplayer_YePlayerHelper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_draculaw_yeplayer_YePlayerHelper
 * Method:    naYepHello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_draculaw_yeplayer_YePlayerHelper_naYepHello
  (JNIEnv *, jobject);

/*
 * Class:     com_draculaw_yeplayer_YePlayerHelper
 * Method:    naInit
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_draculaw_yeplayer_YePlayerHelper_naInit
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_draculaw_yeplayer_YePlayerHelper
 * Method:    naGetVideoRes
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_com_draculaw_yeplayer_YePlayerHelper_naGetVideoRes
  (JNIEnv *, jobject);

/*
 * Class:     com_draculaw_yeplayer_YePlayerHelper
 * Method:    naFinish
 * Signature: (Landroid/graphics/Bitmap;)I
 */
JNIEXPORT jint JNICALL Java_com_draculaw_yeplayer_YePlayerHelper_naFinish
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_draculaw_yeplayer_YePlayerHelper
 * Method:    naGetDuration
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_draculaw_yeplayer_YePlayerHelper_naGetDuration
  (JNIEnv *, jobject);

/*
 * Class:     com_draculaw_yeplayer_YePlayerHelper
 * Method:    naGetFrameRes
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_draculaw_yeplayer_YePlayerHelper_naGetFrameRes
  (JNIEnv *, jobject);

/*
 * Class:     com_draculaw_yeplayer_YePlayerHelper
 * Method:    naGetFrameRate
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_draculaw_yeplayer_YePlayerHelper_naGetFrameRate
  (JNIEnv *, jobject);

/*
 * Class:     com_draculaw_yeplayer_YePlayerHelper
 * Method:    naGetVideoFrame
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_draculaw_yeplayer_YePlayerHelper_naGetVideoFrame
  (JNIEnv *, jobject);

/*
 * Class:     com_draculaw_yeplayer_YePlayerHelper
 * Method:    naPrepareDisplay
 * Signature: (Landroid/graphics/Bitmap;II)I
 */
JNIEXPORT jint JNICALL Java_com_draculaw_yeplayer_YePlayerHelper_naPrepareDisplay
  (JNIEnv *, jobject, jobject, jint, jint);

/*
 * Class:     com_draculaw_yeplayer_YePlayerHelper
 * Method:    naStartDecodeVideo
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_draculaw_yeplayer_YePlayerHelper_naStartDecodeVideo
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
